# Android Signing Properties
# INSTRUCTIONS: Fill in the following properties to sign your release builds.
# storeFile should be the absolute path to your .jks or .keystore file.
# Example: storeFile=D:\\keys\\Android\\upload-key.jks (Use double backslashes on Windows)

storePassword=01032418
keyPassword=01032418
keyAlias=key
storeFile=/Users/neryad/Keys/Android/key.jks
